
---
events:
  -
    kind: "message-v1"
    backtrace:
      - "/home/j4ck/.local/share/JetBrains/Toolbox/apps/clion/bin/cmake/linux/x64/share/cmake-3.27/Modules/CMakeDetermineSystem.cmake:211 (message)"
      - "CMakeLists.txt:2 (project)"
    message: |
      The system is: Linux - 6.7.8-arch1-1 - x86_64
  -
    kind: "message-v1"
    backtrace:
      - "/home/j4ck/.local/share/JetBrains/Toolbox/apps/clion/bin/cmake/linux/x64/share/cmake-3.27/Modules/CMakeDetermineCompilerId.cmake:17 (message)"
      - "/home/j4ck/.local/share/JetBrains/Toolbox/apps/clion/bin/cmake/linux/x64/share/cmake-3.27/Modules/CMakeDetermineCompilerId.cmake:64 (__determine_compiler_id_test)"
      - "/home/j4ck/.local/share/JetBrains/Toolbox/apps/clion/bin/cmake/linux/x64/share/cmake-3.27/Modules/CMakeDetermineCCompiler.cmake:123 (CMAKE_DETERMINE_COMPILER_ID)"
      - "CMakeLists.txt:2 (project)"
    message: |
      Compiling the C compiler identification source file "CMakeCCompilerId.c" succeeded.
      Compiler: /usr/bin/x86_64-w64-mingw32-gcc 
      Build flags: 
      Id flags:  
      
      The output was:
      0
      
      
      Compilation of the C compiler identification source "CMakeCCompilerId.c" produced "a.exe"
      
      The C compiler identification is GNU, found in:
        /home/j4ck/Documents/Projects/UDLR/cmake-build-debug/CMakeFiles/3.27.8/CompilerIdC/a.exe
      
  -
    kind: "try_compile-v1"
    backtrace:
      - "/home/j4ck/.local/share/JetBrains/Toolbox/apps/clion/bin/cmake/linux/x64/share/cmake-3.27/Modules/CMakeDetermineCompilerABI.cmake:57 (try_compile)"
      - "/home/j4ck/.local/share/JetBrains/Toolbox/apps/clion/bin/cmake/linux/x64/share/cmake-3.27/Modules/CMakeTestCCompiler.cmake:26 (CMAKE_DETERMINE_COMPILER_ABI)"
      - "CMakeLists.txt:2 (project)"
    checks:
      - "Detecting C compiler ABI info"
    directories:
      source: "/home/j4ck/Documents/Projects/UDLR/cmake-build-debug/CMakeFiles/CMakeScratch/TryCompile-DeH5Md"
      binary: "/home/j4ck/Documents/Projects/UDLR/cmake-build-debug/CMakeFiles/CMakeScratch/TryCompile-DeH5Md"
    cmakeVariables:
      CMAKE_C_FLAGS: ""
      CMAKE_C_FLAGS_DEBUG: "-g"
      CMAKE_EXE_LINKER_FLAGS: ""
    buildResult:
      variable: "CMAKE_C_ABI_COMPILED"
      cached: true
      stdout: |
        Change Dir: '/home/j4ck/Documents/Projects/UDLR/cmake-build-debug/CMakeFiles/CMakeScratch/TryCompile-DeH5Md'
        
        Run Build Command(s): /home/j4ck/.local/share/JetBrains/Toolbox/apps/clion/bin/ninja/linux/x64/ninja -v cmTC_d8126
        [1/2] /usr/bin/x86_64-w64-mingw32-gcc   -fdiagnostics-color=always   -v -o CMakeFiles/cmTC_d8126.dir/CMakeCCompilerABI.c.o -c /home/j4ck/.local/share/JetBrains/Toolbox/apps/clion/bin/cmake/linux/x64/share/cmake-3.27/Modules/CMakeCCompilerABI.c
        Using built-in specs.
        COLLECT_GCC=/usr/bin/x86_64-w64-mingw32-gcc
        Target: x86_64-w64-mingw32
        Configured with: /build/mingw-w64-gcc/src/gcc/configure --prefix=/usr --libexecdir=/usr/lib --target=x86_64-w64-mingw32 --with-bugurl=https://bugs.archlinux.org/ --enable-languages=ada,c,c++,fortran,lto,objc,obj-c++ --enable-shared --enable-static --enable-threads=posix --enable-fully-dynamic-string --enable-libstdcxx-time=yes --enable-libstdcxx-filesystem-ts=yes --with-system-zlib --enable-cloog-backend=isl --enable-lto --enable-libgomp --disable-multilib --enable-checking=release --disable-sjlj-exceptions --with-dwarf2
        Thread model: posix
        Supported LTO compression algorithms: zlib zstd
        gcc version 13.1.0 (GCC) 
        COLLECT_GCC_OPTIONS='-fdiagnostics-color=always' '-v' '-o' 'CMakeFiles/cmTC_d8126.dir/CMakeCCompilerABI.c.o' '-c' '-mtune=generic' '-march=x86-64' '-dumpdir' 'CMakeFiles/cmTC_d8126.dir/'
         /usr/lib/gcc/x86_64-w64-mingw32/13.1.0/cc1 -quiet -v -D_REENTRANT /home/j4ck/.local/share/JetBrains/Toolbox/apps/clion/bin/cmake/linux/x64/share/cmake-3.27/Modules/CMakeCCompilerABI.c -quiet -dumpdir CMakeFiles/cmTC_d8126.dir/ -dumpbase CMakeCCompilerABI.c.c -dumpbase-ext .c -mtune=generic -march=x86-64 -version -fdiagnostics-color=always -o /tmp/ccqYCu4f.s
        GNU C17 (GCC) version 13.1.0 (x86_64-w64-mingw32)
        	compiled by GNU C version 13.2.1 20230801, GMP version 6.3.0, MPFR version 4.2.1, MPC version 1.3.1, isl version isl-0.26-GMP
        
        GGC heuristics: --param ggc-min-expand=100 --param ggc-min-heapsize=131072
        ignoring nonexistent directory "/usr/lib/gcc/x86_64-w64-mingw32/13.1.0/../../../../x86_64-w64-mingw32/sys-include"
        #include "..." search starts here:
        #include <...> search starts here:
         /usr/lib/gcc/x86_64-w64-mingw32/13.1.0/include
         /usr/lib/gcc/x86_64-w64-mingw32/13.1.0/include-fixed
         /usr/lib/gcc/x86_64-w64-mingw32/13.1.0/../../../../x86_64-w64-mingw32/include
        End of search list.
        Compiler executable checksum: 9de5ef3d2806eb3f01b8efd28c620ff4
        COLLECT_GCC_OPTIONS='-fdiagnostics-color=always' '-v' '-o' 'CMakeFiles/cmTC_d8126.dir/CMakeCCompilerABI.c.o' '-c' '-mtune=generic' '-march=x86-64' '-dumpdir' 'CMakeFiles/cmTC_d8126.dir/'
         /usr/lib/gcc/x86_64-w64-mingw32/13.1.0/../../../../x86_64-w64-mingw32/bin/as -v -o CMakeFiles/cmTC_d8126.dir/CMakeCCompilerABI.c.o /tmp/ccqYCu4f.s
        GNU assembler version 2.39 (x86_64-w64-mingw32) using BFD version (GNU Binutils) 2.39
        COMPILER_PATH=/usr/lib/gcc/x86_64-w64-mingw32/13.1.0/:/usr/lib/gcc/x86_64-w64-mingw32/13.1.0/:/usr/lib/gcc/x86_64-w64-mingw32/:/usr/lib/gcc/x86_64-w64-mingw32/13.1.0/:/usr/lib/gcc/x86_64-w64-mingw32/:/usr/lib/gcc/x86_64-w64-mingw32/13.1.0/../../../../x86_64-w64-mingw32/bin/
        LIBRARY_PATH=/usr/lib/gcc/x86_64-w64-mingw32/13.1.0/:/usr/lib/gcc/x86_64-w64-mingw32/13.1.0/../../../../x86_64-w64-mingw32/lib/../lib/:/usr/lib/gcc/x86_64-w64-mingw32/13.1.0/../../../../x86_64-w64-mingw32/lib/
        COLLECT_GCC_OPTIONS='-fdiagnostics-color=always' '-v' '-o' 'CMakeFiles/cmTC_d8126.dir/CMakeCCompilerABI.c.o' '-c' '-mtune=generic' '-march=x86-64' '-dumpdir' 'CMakeFiles/cmTC_d8126.dir/CMakeCCompilerABI.c.'
        [2/2] : && /usr/bin/x86_64-w64-mingw32-gcc  -v CMakeFiles/cmTC_d8126.dir/CMakeCCompilerABI.c.o -o cmTC_d8126   && :
        Using built-in specs.
        COLLECT_GCC=/usr/bin/x86_64-w64-mingw32-gcc
        COLLECT_LTO_WRAPPER=/usr/lib/gcc/x86_64-w64-mingw32/13.1.0/lto-wrapper
        Target: x86_64-w64-mingw32
        Configured with: /build/mingw-w64-gcc/src/gcc/configure --prefix=/usr --libexecdir=/usr/lib --target=x86_64-w64-mingw32 --with-bugurl=https://bugs.archlinux.org/ --enable-languages=ada,c,c++,fortran,lto,objc,obj-c++ --enable-shared --enable-static --enable-threads=posix --enable-fully-dynamic-string --enable-libstdcxx-time=yes --enable-libstdcxx-filesystem-ts=yes --with-system-zlib --enable-cloog-backend=isl --enable-lto --enable-libgomp --disable-multilib --enable-checking=release --disable-sjlj-exceptions --with-dwarf2
        Thread model: posix
        Supported LTO compression algorithms: zlib zstd
        gcc version 13.1.0 (GCC) 
        COMPILER_PATH=/usr/lib/gcc/x86_64-w64-mingw32/13.1.0/:/usr/lib/gcc/x86_64-w64-mingw32/13.1.0/:/usr/lib/gcc/x86_64-w64-mingw32/:/usr/lib/gcc/x86_64-w64-mingw32/13.1.0/:/usr/lib/gcc/x86_64-w64-mingw32/:/usr/lib/gcc/x86_64-w64-mingw32/13.1.0/../../../../x86_64-w64-mingw32/bin/
        LIBRARY_PATH=/usr/lib/gcc/x86_64-w64-mingw32/13.1.0/:/usr/lib/gcc/x86_64-w64-mingw32/13.1.0/../../../../x86_64-w64-mingw32/lib/../lib/:/usr/lib/gcc/x86_64-w64-mingw32/13.1.0/../../../../x86_64-w64-mingw32/lib/
        COLLECT_GCC_OPTIONS='-v' '-o' 'cmTC_d8126.exe' '-mtune=generic' '-march=x86-64' '-dumpdir' 'cmTC_d8126.'
         /usr/lib/gcc/x86_64-w64-mingw32/13.1.0/collect2 -plugin /usr/lib/gcc/x86_64-w64-mingw32/13.1.0/liblto_plugin.so -plugin-opt=/usr/lib/gcc/x86_64-w64-mingw32/13.1.0/lto-wrapper -plugin-opt=-fresolution=/tmp/cci17aTE.res -plugin-opt=-pass-through=-lmingw32 -plugin-opt=-pass-through=-lgcc -plugin-opt=-pass-through=-lgcc_eh -plugin-opt=-pass-through=-lmoldname -plugin-opt=-pass-through=-lmingwex -plugin-opt=-pass-through=-lmsvcrt -plugin-opt=-pass-through=-lkernel32 -plugin-opt=-pass-through=-lpthread -plugin-opt=-pass-through=-ladvapi32 -plugin-opt=-pass-through=-lshell32 -plugin-opt=-pass-through=-luser32 -plugin-opt=-pass-through=-lkernel32 -plugin-opt=-pass-through=-lmingw32 -plugin-opt=-pass-through=-lgcc -plugin-opt=-pass-through=-lgcc_eh -plugin-opt=-pass-through=-lmoldname -plugin-opt=-pass-through=-lmingwex -plugin-opt=-pass-through=-lmsvcrt -plugin-opt=-pass-through=-lkernel32 -m i386pep -Bdynamic -o cmTC_d8126.exe /usr/lib/gcc/x86_64-w64-mingw32/13.1.0/../../../../x86_64-w64-mingw32/lib/../lib/crt2.o /usr/lib/gcc/x86_64-w64-mingw32/13.1.0/crtbegin.o -L/usr/lib/gcc/x86_64-w64-mingw32/13.1.0 -L/usr/lib/gcc/x86_64-w64-mingw32/13.1.0/../../../../x86_64-w64-mingw32/lib/../lib -L/usr/lib/gcc/x86_64-w64-mingw32/13.1.0/../../../../x86_64-w64-mingw32/lib CMakeFiles/cmTC_d8126.dir/CMakeCCompilerABI.c.o -lmingw32 -lgcc -lgcc_eh -lmoldname -lmingwex -lmsvcrt -lkernel32 -lpthread -ladvapi32 -lshell32 -luser32 -lkernel32 -lmingw32 -lgcc -lgcc_eh -lmoldname -lmingwex -lmsvcrt -lkernel32 /usr/lib/gcc/x86_64-w64-mingw32/13.1.0/crtend.o
        COLLECT_GCC_OPTIONS='-v' '-o' 'cmTC_d8126.exe' '-mtune=generic' '-march=x86-64' '-dumpdir' 'cmTC_d8126.'
        
      exitCode: 0
  -
    kind: "try_compile-v1"
    backtrace:
      - "/home/j4ck/.local/share/JetBrains/Toolbox/apps/clion/bin/cmake/linux/x64/share/cmake-3.27/Modules/CMakeTestCCompiler.cmake:56 (try_compile)"
      - "CMakeLists.txt:2 (project)"
    checks:
      - "Check for working C compiler: /usr/bin/x86_64-w64-mingw32-gcc"
    directories:
      source: "/home/j4ck/Documents/Projects/UDLR/cmake-build-debug/CMakeFiles/CMakeScratch/TryCompile-KI4QXI"
      binary: "/home/j4ck/Documents/Projects/UDLR/cmake-build-debug/CMakeFiles/CMakeScratch/TryCompile-KI4QXI"
    cmakeVariables:
      CMAKE_C_FLAGS: ""
      CMAKE_C_FLAGS_DEBUG: "-g"
      CMAKE_EXE_LINKER_FLAGS: ""
    buildResult:
      variable: "CMAKE_C_COMPILER_WORKS"
      cached: true
      stdout: |
        Change Dir: '/home/j4ck/Documents/Projects/UDLR/cmake-build-debug/CMakeFiles/CMakeScratch/TryCompile-KI4QXI'
        
        Run Build Command(s): /home/j4ck/.local/share/JetBrains/Toolbox/apps/clion/bin/ninja/linux/x64/ninja -v cmTC_dad68
        [1/2] /usr/bin/x86_64-w64-mingw32-gcc   -fdiagnostics-color=always -o CMakeFiles/cmTC_dad68.dir/testCCompiler.c.o -c /home/j4ck/Documents/Projects/UDLR/cmake-build-debug/CMakeFiles/CMakeScratch/TryCompile-KI4QXI/testCCompiler.c
        [2/2] : && /usr/bin/x86_64-w64-mingw32-gcc   CMakeFiles/cmTC_dad68.dir/testCCompiler.c.o -o cmTC_dad68   && :
        
      exitCode: 0
...
